; PlatformIO Project Configuration File for Lab 3: LED Toggle ON / OFF
[platformio]
src_dir = src
include_dir = include

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    mathieucarbou/ESPAsyncWebServer @ ^3.6.0
build_flags = 
    -D CORE_DEBUG_LEVEL=0
